server {
    listen @PUBLIC_NON_SSL_IP@:@PUBLIC_NON_SSL_PORT@;
    server_name @SERVER_NAME@;
    root @WEB_ROOT_PATH@;

    client_max_body_size 0;

    access_log @ACCESS_LOG_FILE@;
    error_log @ERROR_LOG_FILE@;

    # Allow direct Let's Encrypt HTTP-01 challenge pass-through
    location /.well-known/acme-challenge/ {
        root @WEB_ROOT_PATH@;
        try_files $uri =404;
    }

    # Redirect everything else to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}
