server {
    listen @PUBLIC_SSL_IP@:@PUBLIC_SSL_PORT@ ssl http2;
    server_name @SERVER_NAME@;
    root @WEB_ROOT_PATH@;

    client_max_body_size 0;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_certificate @SSL_CERTIFICATE@;
    ssl_certificate_key @SSL_CERTIFICATE_KEY@;

    access_log @ACCESS_LOG_FILE@;
    error_log @ERROR_LOG_FILE@;

    # Static contents with fallback to Apache
    location ~* \.(jpg|jpeg|gif|png|ico|css|zip|tgz|gz|rar|bz2|doc|xls|exe|pdf|ppt|txt|tar|mid|midi|wav|bmp|rtf|js|svg|webp|woff|woff2)$ {
        expires max;
        try_files $uri @apache;
    }

	# 1. Main location block checks disk first
	location / {
		try_files $uri $uri/ @apache;
	}

	# 2. Named fallback location forwards non-static/missing requests to Apache
    location @apache {
        proxy_pass https://@APACHE_SSL_IP@:@APACHE_SSL_PORT@;
		
		# Pass the domain name in the TLS SNI extension to fix HTTP 421
		proxy_ssl_server_name on;
		proxy_ssl_name $host;
		
		# Bypass backend certificate validation (loopback connection)
		proxy_ssl_verify off;
		proxy_ssl_session_reuse on;

		# Enable HTTP/1.1 persistent connections (prevents reopening TLS sockets)
		proxy_http_version 1.1;
		proxy_set_header Connection "";

		# Forward client metadata to Apache
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_set_header X-Forwarded-Port 443;
    }
}
